{"timestamp": "2025-06-07T23:44:15.496651", "level": "ERROR", "logger": "test_logger", "message": "エラーメッセージ", "module": "logger", "function": "_log", "line": 201}
{"timestamp": "2025-06-07T23:44:15.496651", "level": "ERROR", "logger": "test_logger", "message": "ゼロ除算エラー発生", "module": "logger", "function": "_log", "line": 201, "exception": "Traceback (most recent call last):\n  File \"N:\\python_projects\\check_company_with_web\\tests\\test_logger.py\", line 19, in test_logger\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
